- name: azure
  by: Sennoma-Nn
  tag: Minimalist

- name: power-blocks
  by: Sennoma-Nn
  tag: Power Line

- name: gxy
  by: Sennoma-Nn
  tag: Power Line, Multiple Lines

- name: neon-night
  by: Sennoma-Nn
  tag: Multiple Lines

- name: retro-console
  by: Sennoma-Nn
  tag: Retro

- name: simple-minimal
  by: Sennoma-Nn
  tag: Minimalist

- name: galaxy-dream
  by: Sennoma-Nn
  tag: Emoji, Multiple Lines

- name: sunset-ocean
  by: Sennoma-Nn
  tag: Power Line, Multiple Lines
